### ISSUE TITLE
Formatting Topic Data Preview

### ISSUE THREAD

**Issue by Wihmajster** [rxsio/robot-web-interface#14]
We should enhance the topic data preview window to allow users to select and display specific values from the message, rather than showing the entire message in JSON format. The user will be able to define which fields to display and set custom labels. For example, instead of the full JSON message:

```
{
  header:
    stamp: 
      seconds: <data>
      nanoseconds: <data>
    frame_id: <data>
  radiation:
    cpm: <data>
    dose: <data>
  some_other_stuff: <data>
}
```

The preview could be formatted to show only the following:

```
Seconds: <data>
Nanoseconds: <data>
CPM: <data>
Dose: <data>
```

<sub><a href="https://huly.app/guest/rxsio?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzBkYTI5NjhkY2MwMDM2MTU1YWU4OTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2FicmllbC1yeHNpby02NjY4NDU2NC0yYzJmNWM5M2IzLWFmOTBiNyJ9.CnORDTNbP0dB7RZnbXn_jDypvMKbMuqRYGRzJZX-bKM">Huly&reg;: <b>FIRO_-32</b></a></sub>
